# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='country',
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_line1',
            field=models.CharField(max_length=255, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_line2',
            field=models.CharField(max_length=255, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_line3',
            field=models.CharField(max_length=255, null=True, verbose_name='Address line 3'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='address_street',
            field=models.CharField(max_length=255, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='alt_email',
            field=models.CharField(max_length=50, null=True, verbose_name='Alternative E-mail'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='mobile_phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='mobile_work_phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Mobile work phone'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='region',
            field=models.CharField(max_length=50, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='skype',
            field=models.CharField(max_length=50, null=True, verbose_name='Skype'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='telegram',
            field=models.CharField(max_length=50, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='viber',
            field=models.CharField(max_length=50, null=True, verbose_name='Viber'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='whatsapp',
            field=models.CharField(max_length=50, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='work_phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Work phone'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='zip_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Zip code'),
        ),
        migrations.AddField(
            model_name='person',
            name='accountable_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='address_line1',
            field=models.CharField(max_length=255, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_line2',
            field=models.CharField(max_length=255, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_line3',
            field=models.CharField(max_length=255, null=True, verbose_name='Address line 3'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_street',
            field=models.CharField(max_length=255, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='person',
            name='alt_email',
            field=models.CharField(max_length=50, null=True, verbose_name='Alternative E-mail'),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='User name'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='person',
            name='mid_name',
            field=models.CharField(max_length=30, null=True, verbose_name='User name'),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile_phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile_work_phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Mobile work phone'),
        ),
        migrations.AddField(
            model_name='person',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Organisation'),
        ),
        migrations.AddField(
            model_name='person',
            name='region',
            field=models.CharField(max_length=50, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='person',
            name='skype',
            field=models.CharField(max_length=50, null=True, verbose_name='Skype'),
        ),
        migrations.AddField(
            model_name='person',
            name='telegram',
            field=models.CharField(max_length=50, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='person',
            name='update_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='viber',
            field=models.CharField(max_length=50, null=True, verbose_name='Viber'),
        ),
        migrations.AddField(
            model_name='person',
            name='whatsapp',
            field=models.CharField(max_length=50, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Work phone'),
        ),
        migrations.AddField(
            model_name='person',
            name='zip_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Zip code'),
        ),
    ]
